INSERT INTO
twitter.dbo.Users
(first_name,last_name,email,userPassword)
VALUES
('Ion','Tigan','ion.tigan@gmail.com','endavatest'),
('Alex','Lungu','alex.lungu@gmail.com','endavatest'),
('Octavian','Lungu','octagto@gmail.com','endavatest'),
('Alina','Puia','alina.puia@gmail.com','endavatest'),
('Ion','Doibani','iondoibani@gmail.com','endavatest'),
('Vladimir','Morari','vladimir87@gmail.com','endavatest'),
('Ion','Sinigur','sinigur@gmail.com','endavatest'),
('Cristina','Pusca','puscacristina@gmail.com','endavatest'),
('Grigore','Vasilachi','grigorev@gmail.com','endavatest'),
('Gheorghe','Vashilache','vasilachi.jorj@gmail.com','endavatest'),
('Vlad','Picireanu','picireanuvlad@gmail.com','endavatest'),
('Daniel','Munteanu','munteanu@gmail.com','endavatest'),
('Adrian','Calancea','acalancea@gmail.com','endavatest'),
('Vasile','Chiriliuc','chirvasile@gmail.com','endavatest'),
('Vasile','Cudalb','vasile.cudalb@gmail.com','endavatest'),
('Roman','Bugaci','bugaciRoman@gmail.com','endavatest'),
('Eugen','Popodneac','popodneac@gmail.com','endavatest'),
('Ecaterina','Levitchi','sunEca@gmail.com','endavatest'),
('Alina','Levitchi','alieva@gmail.com','endavatest'),
('Ion','Scorobogaci','ion.scorobogaci@gmail.com','123456789'),
('Eugen','Papuc','papuceugen@gmail.com','endavatest'),
('Alex','Papuc','pepux@gmail.com','endavatest'),
('Roman','Para','superpara@gmail.com','endavatest'),
('Pavel','Miron','pavelmiron@gmail.com','endavatest');

