//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int id_follow { get; set; }
        public int id_subscriber { get; set; }
        public int id_followed_user { get; set; }
    }
}
