//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public int id_tweet { get; set; }
        public string descripton { get; set; }
        public int id_user { get; set; }
        public byte[] created_on { get; set; }
    }
}
